### ISSUE TITLE
MIT App Inventor

### ISSUE THREAD

**Issue by GrantPerkins** [tm1287/If-Else-Excercises#1]
I love writing code from Scratch!

**Comment by tm1287** [comment]
From, or In Scratch

**Comment by tm1287** [comment]
Cause this was supposed to be my first real submitted project I would do in android studio. But then I gave up with the whole VCS stuff and decided to just store my apps locally

**Comment by tm1287** [comment]
And stop snooping around in my repos

**Comment by GrantPerkins** [comment]
Aww man
